---
- name: Configuring the EC2 Instance
  hosts: localhost
  connection: local
 
  tasks:
  - name: Launching an EC2 Instance
    local_action: ec2
                aws_access_key={{ aws_access_key }}
                aws_secret_key={{ aws_secret_key }}
                group={{ security_group }}
                instance_type={{ instance_type }}
                image={{ image }}
                region={{ region }}
                wait=true
                keypair={{ keypair }}
                count={{ count }}
                vpc_subnet_id={{ vpc_subnet_id }}
                assign_public_ip=yes
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
    with_items: "{{ ec2.instances }}" 

  - name: Add new instances to host group
    add_host: hostname="{{ item.public_dns_name }}" groupname=deploy
    with_items: "{{ ec2.instances }}"

- name: Configure instance
  hosts: deploy
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Install NTP Server
      yum: pkg=ntp state=latest

    - name: Ensure NTP is up and running
      service: name=ntpd state=started

    - name: Install Apache Web Server
      yum: pkg=httpd state=latest

    - name: Ensure httpd is up and running
      service: name=httpd state=started

